### PR TITLE
Add asJSON for difftime

### PR DESCRIPTION
**Pull request by andresperezl**
asJSON difftime has two options:
`string` : that will return the difference of time as a sentence, e.g: `2 secs`, `2 mins`, etc
`epoch`: that will return the plain number of seconds difference as a integer

### CODE REVIEW

**Comment by jeroen** [comment]
So if you encode difftime as number, it just drops the unit and gives you a value but you don't know if those are seconds or minutes or hours? Isn't that dangerous?

**Comment by andresperezl** [comment]
Yes, it will look at the unit and do the proper conversion

**Comment by andresperezl** [comment]
@jeroen can you help me out a little bit with the documentation, is the reason that travis is falling

**Comment by jeroen** [comment]
Something has gone wrong in your `roxygenize()`... it has dropped most of the `toJSON` documentation. Which version of roxygen2 do you have?

**Comment by andresperezl** [comment]
@jeroen 6.0.1.9000

**Comment by jeroen** [comment]
Can you try to roxygenize with the cran version 6.0.1?

**Comment by jeroen** [comment]
Also what you're doing for `epoch` seems completely broken?
```
> toJSON(hms::as.hms(1:10), difftime = 'epoch')
[1] 
```

I think you should simply use `as.numeric(x, units = "secs")`?

**Comment by andresperezl** [comment]
Now I got this:

```
> roxygen2::roxygenize(".")
in method for ‘asJSON’ with signature ‘"difftime"’: no definition for class “difftime”
Warning message:
Version of roxygen2 last used with this package is 6.0.1.9000.  You only have version 6.0.1 
```

**Pull request closed without merging**
