### PR TITLE
Add asJSON method for ITime

### LINKED ISSUE #327: Should new class for asJSON method be defined in jsonlite?
A user of DT raises [an issue](https://github.com/rstudio/DT/issues/840), which is due to the missing method of `asJSON()` for `ITime`. The latter is an S3 class defined by the data.table package and is used for storing the time-of-day values.

Adding the below code in jsonlite will resolve the user's issue (I've tested it) but I'm not sure if this is the right way to go.

I mean, should this method be defined in jsonlite or should it be defined in the data.table package (is it possible to do)? 

If defining the method in jsonlite is desired, I can help to file a PR later.

Thanks!

```r
setMethod("asJSON", "ITime", function(x, ...) {
  asJSON(as.character(x), ...)
})
```

### PR DESCRIPTION
**Pull request by shrektan**
Closes #327 
Fixes rstudio/DT#840

Thanks!

### CODE REVIEW

**Comment by jeroen** [comment]
CMD check shows 

```
 checking for unstated dependencies in ‘tests’ ... WARNING
'::' or ':::' import not declared from: ‘data.table’
```

Can you please replace `data.table::as.ITime("12:00:00")` with `structure(43200L, class = "ITime")` in the test?

**Comment by shrektan** [comment]
Replacing data.table::as.ITime("12:00:00") with structure(43200L, class = "ITime") alone will lead to the test failure, as "data.table" namespace won't be loaded thus the S3 method `as.character.ITime()` won't be available.

However, having `requireNamespace("data.table")` will lead to the same error in R CMD Check...

So, I think I may have to remove the test... Is this ok for you?

**Comment by jeroen** [comment]
OK let's just remove the test.

**Comment by shrektan** [comment]
Removed :D

**Pull request merged**
