### PR TITLE
fromJSON() supports functions in simplifyDataFrame argument

### LINKED ISSUE #356: Optionally create tibbles instead of data frames in fromJSON()
Converting all nested data frames to tibbles is a very cumbersome exercise, tibble's output is more compact for nested data. Would you consider an optional argument to `fromJSON()` ?

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #356.

I made the change as minimal as possible, perhaps at the expense of clarity. Should the internal `simplifyToDataFrame` argument perhaps be renamed to `coerceDataFrame` or similar?

### CODE REVIEW

**Comment by krlmlr** [comment]
Tests pass, finally.

**Comment by jeroen** [comment]
Thanks, sorry this code is a mess, it is very old.

**Comment by krlmlr** [comment]
The code is fine, it does its job. The tests are good and caught a corner case I would have missed.

Let me know if you'd like me to tweak something along the way.

**Comment by krlmlr** [comment]
Maybe we can export `simplify()` ?

**Comment by krlmlr** [comment]
Just a heads-up: I'm starting to use this in production, so far it works really well and is a great help.

**Comment by krlmlr** [comment]
Closing this in favor of tibblify and arrow.

**Comment by jeroen** [comment]
I'm sorry I never got to merging this.

**Pull request closed without merging**
