### PR TITLE
WIP: Avoid calling setOldClass(blob)

### LINKED ISSUE #373: Messages when loading blob and jsonlite
```
      Found more than one class "blob" in cache; using the first, from namespace 'blob'
      Also defined by 'jsonlite'
```

See e.g. https://github.com/cynkra/dm/pull/745/files#diff-7d82583ffca8693518bbd7850f257dc85176e3b79287e7bcb2388665d0c25aaeR6 .

Not sure how to trigger it. Most likely caused by 927cf6ef6262733ecfd6124780b2de08db91f27e.

Perhaps you could call `setMethod()` lazily, when the blob package is loaded?

### PR DESCRIPTION
**Pull request by krlmlr**
Opening PR to reproduce problem when the call is missing.

Will close #373.

### CODE REVIEW

**Comment by krlmlr** [comment]
@jeroen: What warning did 927cf6ef6262733ecfd6124780b2de08db91f27e fix? The checks don't show any failures.

**Comment by jeroen** [comment]
The exact opposite warning (setting method without defining a class). I think these warnings only appear in --as-cran or something because I am not seeing your warning either.

**Comment by krlmlr** [comment]
Sending this to winbuilder now.

What system has shown that other warning to you?

**Comment by krlmlr** [comment]
winbuilder seems satisfied too. Could it be that the warning happens on older versions of R?

**Comment by krlmlr** [comment]
Of course: I only see the warnings with R 3.6 . I haven't found anything in the news for R >= 4.0.0, unfortunately.

**Comment by jeroen** [comment]
Ugh I don't remember exactly, I think it the warning was there maybe only when loaded with another pkg. Let me see if I can reproduce anything.

**Comment by krlmlr** [comment]
I'm seeing the following with this branch:

``` r
library(jsonlite)
toJSON(structure(list(raw()), class = "blob"))
#> [""]
getClassDef("blob")
#> NULL

library(blob)
toJSON(structure(list(raw()), class = "blob"))
#> [""]
getClassDef("blob")
#> Virtual Class "blob" [package "blob"]
#> 
#> Slots:
#>                 
#> Name:   .S3Class
#> Class: character
#> 
#> Extends: 
#> Class "vctrs_list_of", directly
#> Class "vctrs_vctr", by class "vctrs_list_of", distance 2
#> Class "oldClass", by class "vctrs_list_of", distance 3
```

<sup>Created on 2022-01-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

As the CRAN checks succeed and jsonlite doesn't own the `"blob"` class, maybe the PR is good as is?

**Comment by jeroen** [comment]
I am sure this was triggering another message in some situation about setting a method on a class that was not defined.

**Comment by krlmlr** [comment]
Should we run a revdepcheck for this branch?

**Comment by krlmlr** [comment]
Started a revdepcheck on all 4000 direct and indirect dependencies on CRAN.

**Comment by krlmlr** [comment]
Revdeps look clean.

In R 3.6 I see:

```
> devtools::load_all(".")
Loading jsonlite
in method for ‘asJSON’ with signature ‘"blob"’: no definition for class “blob”
```

Maybe if we called `setOldClass()` only for R 3.6 and earlier?

**Comment by jeroen** [comment]
> Maybe if we called setOldClass() only for R 3.6 and earlier?


OK let's to do that then.

**Comment by krlmlr** [comment]
The other question is: does `asJSON()` really need to be an S4 generic? There is a method for `classRepresentation`, would that work if `asJSON()` was an S3 generic? It seems that this method isn't even exposed, so no risk to break downstream?

I'm asking because I'm seeing a few more instances of `setOldClass()`, all are potential disasterettes waiting to happen.

**Comment by jeroen** [comment]
Yes it would probably be better to get rid of S4 but I'm not sure it's worth the effort right now. Fortunately these messages seem mostly harmless, both the old one `in method for ‘asJSON’ with signature ‘"blob"’: no definition for class “blob”` and the new one `Found more than one class "blob" in cache; using the first, from namespace 'blob'`. It would be good to figure out if something in R has changed such that we should no longer call `setOldClass()`

**Pull request closed without merging**
