### PR TITLE
Add contributing guide and Code of Conduct.

### PR DESCRIPTION
**Pull request by batpigandme**
Add a contributing guide and Code of Conduct.

This is in order to publish a paper in JOSS re. the tidyverse. Please let me know if there are any changes you'd like me to make, or if these guides don't work well for you.

Thanks, @jeroen!

Mara

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks... Given that I am neither an author of the paper, nor is jsonlite referenced anywhere in the tidyverse paper, how exactly is the tidyverse contributor guide relevant for this project?

**Comment by batpigandme** [comment]
Yeah…good question, and it's the same one we're being asked in the review. Now that I look at it more closely, it seems like the CONTRIBUTING.md doesn't make sense here (happy to delete that from this PR). I'm about to respond to the paper review (https://github.com/openjournals/joss-reviews/issues/1686) with the same below (per @hadley's description):
> The xml2, httr, jsonlite, and feather package have a somewhat murky relationship to the tidyverse. These packages are mostly installed because we expect them to be used pretty frequently but are owned by other organisations. 

I'll await Hadley's guidance re. authorship, because it does make sense to me that if an entire package is installed with the tidyverse, then its author(s) (e.g. you) would _ipso facto_ become package authors.

**Comment by hadley** [comment]
I don't think there's any requirement for jsonlite to adopt the same requirements, except that having a code of conduct and a `LICENSE.md` seem to be good practice in general.

**Comment by jeroen** [comment]
I do think it's a bit odd how this paper seemingly takes credit instead of gives credit for external work that the tidyverse builds upon. I think you should at least consider citing packages like magrittr and jsonlite that are not written by any of the paper authors but still part of the work that is presented.

**Comment by hadley** [comment]
We're not attempting to take credit for your or anyone else's work. I think there was just a miscommunication between the reviewer, myself, and Mara: jsonlite is imported by the tidyverse package (because we believe it to be a useful tool that analysts need), but it's not part of the tidyverse (because you wrote it). That's why it's not currently mentioned in the paper, but we're happy to add it if you think it's important.

**Comment by hadley** [comment]
Re-reading the paper, particularly this paragraph:

> Non-core packages are installed with install.packages("tidyverse"), but are not attached by library(tidyverse). They play more specialised roles, so will be attached by the analyst as needed. The non-core packages are: blob [@R-blob], feather [@R-feather], glue [@R-glue], googledrive [@R-googledrive], haven [@R-haven], hms [@R-hms], lubridate [@R-lubridate], magrittr [@R-magrittr], modelr [@R-modelr], readxl [@R-readxl], reprex [@R-reprex], and rvest [@R-rvest].

It does seem odd that we've omitted jsonlite — apologies! We'll add something like:

> We also import one package that's not technically in the tidyverse, but is so commonly used that you can't survive long without it: jsonlite [@R-jsonlite].

**Comment by hadley** [comment]
Alternatively, we could avoid the awkwardness of the additional sentence by listing jsonlite with the other non-core packages and adding you as a co-author of the paper. Let us know what you'd prefer.

**Comment by jeroen** [comment]
I'd be very honored to be a co-author of course. If the tidyverse can't survive without jsonlite, and the package attaches it so that it is part of the standard workflow, and you've already named it as part of the package list in the journal submission, I think that's not unreasonable :) Thanks!

**Comment by batpigandme** [comment]
👍  Sounds good to me. What's your preferred affiliation, @jeroen?

**Comment by jeroen** [comment]
`Berkeley Institute for Data Science, University of California, Berkeley`

**Pull request merged**
